#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD socket server
# Description:       Socket server for AESD assignment
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
NAME=aesdsocket
PIDFILE=/var/run/aesdsocket.pid

case "$1" in
    start)
        echo "Starting $NAME"
        start-stop-daemon -S -n $NAME -a $DAEMON -- -d
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon -K -n $NAME -s TERM
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
